name: Debugger
on:
  workflow_dispatch:
jobs:
  build:
    name: Debug Github Actions
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - run: echo "hello!"