name: Debugger
on:
  workflow_dispatch:
jobs:
  build:
    name: Debug Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref_name }}
